description: Account and usage information for IFB customer applications
properties:
  applicationName:
    type: string
  accountName:
    type: string
  registrationDate:
    type: string
    format: date
  lastLoginDate:
    type: string
    format: date
