swagger: "2.0"
info:
  version: 0.0.0
  title: DefinitionsStub
  description: Definitions Stub - Do Not Deploy
paths:
  /foo:
    get:
      summary: Stub, do not deploy
      responses:
        "200":
          description: Success
definitions:
  $ref: ../definitions.yaml#/definitions

