swagger: '2.0'
info:
  version: 1.0.0
  title: archive
  description: |
    A [system](http://connections/issite/iCAF/SitePages/APIs%20-%20System%20vs%20Process%20vs%20Experience.aspx) layer API.

    #### Service Functionality
    * Archive document to the ImageRight system. Uses the putfiles service.

    #### Sequence Diagram
    ![Interaction](http://connections/issite/ews/SiteAssets/api.system.archive-design.png)

    #### Known Implementations
    * Care+ Review

    #### Performance Expectation
    Standard SLA applies.
    
    #### Service Capacity Supported
    Standard Capacity applies
    
    #### Suggested Test Scenario
    TBD
    
    #### Service Availability
    Standard Service Availability applies
    
    #### Service Security
    HTTPS/SSL
  contact:
    name: Enterprise Web Services Team
    email: EWSDevelopers@infambureau.com
    url: http://connections/issite/ews/SitePages/Home.aspx
schemes:
  - 'https'
  - 'http'
consumes:
  - 'application/json'
produces:
  - 'application/json'
host:
  ap-karafb-dev:8181
basePath:
  /api/archive
paths:
  /:
    post:
      summary:  Archive document
      description: |
        Archive document in ImageRight system.
      parameters:
        - name:  archive-request
          in: body
          description: The input paramters in JSON format
          required: true
          schema:
            $ref: '../definitions.yaml#/definitions/archive-request'
      responses:
        '201':
          description: |
            Created.  No content is returned.
        default:
          description: |
            Failure.
