swagger: "2.0"
info:
  version: 1.0.0
  title: client-businesses-name
  x-architectural-layer: system
  description: |
    This is a system level API that updates the client name for businesses

    #### Service Functionality
    This API is called with a {clientId} parameter. If successful, the resultant is a HTTP 200 status code.

    #### Diagrams
    TBD

    #### Performance Expectation
    Standard SLA applies.

    #### Service Capacity Supported
    Standard Capacity applies

    #### Suggested Test Scenario
    TBD

    #### Service Availability
    Standard Service Availability applies

    #### Service Security
    HTTPS/SSL

  contact:
    name:  Mary Boscaccia
    url:  http://www.infarmbureau.com
    email: mary.Boscacci@infarmbureau.com
produces:
  - application/json
schemes:
  - http
  - https
basePath:
  /api/clients/businesses
paths:
  /{clientId}/name:
    post:
      summary: Corrects client name
      description: For a given clientId, corrects the client name for business client type.
      parameters:
          - $ref: '#/parameters/ClientId'
          - name: client-businesses-name-request
            description: The desired business name information for this operation
            required: true
            in: body
            schema:
              $ref: '../definitions.yaml#/definitions/client-businesses-name-request'
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized or invalid token
        '404':
          description: Entity not found
        '500':
          description: Server error
    'put':
      summary: Changes client name
      description: For a given clientId, changes the client name for business client type.
      parameters:
        - $ref: '#/parameters/ClientId'
        - name: client-businesses-name-request
          description: The desired business name information for this operation
          required: true
          in: body
          schema:
            $ref: '../definitions.yaml#/definitions/client-businesses-name-request'
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized or invalid token
        '404':
          description: Entity not found
        '500':
          description: Server error
parameters:
  ClientId:
    description: The identifier of the client
    name: clientId
    required: true
    in: path
    type: string