swagger: "2.0"
info:
  version: 2.0.0
  title: Clients
  description: |
    This is the entry point for client inquiries.

    #### Service Functionality:
    This API is called with a clientId parameter.  If successful, the resultant resource is a
    JSON oject, based on the Client model.

    #### Instance Diagram(s) 
    ![Client](http://connections/issite/ews/SiteAssets/path-clients.png)

    #### Performance Expectation:
    Standard SLA applies.
    
    #### Service Capacity Supported:
    Standard Capacity applies
    
    #### Suggested Test Scenario:
    TBD
    
    #### Service Availability:
    Standard Service Availability applies
    
    #### Service Security:
    HTTPS/SSL
  contact:
    name:  Mary Boscaccia
    url:  http://www.infarmbureau.com
    email: mary.Boscacci@infarmbureau.com
produces:
  - application/json
schemes:
  - https
basePath: /clients
paths:
  /{clientId}/:
    get:
      x-auth-type: "Application & Application User"
      x-scope: api_read
      x-throttling-tier: Unlimited
      summary: Returns a array of Client models identified by the clientId
      description: |
        This process layer service queries the client record keeping system (Exceed) using the submitted parameter (clientId).   A detailed Client is returned, if the clientId exists.
      externalDocs:
        description: Client Instance Diagram
        url: http://connections/issite/ews/SiteAssets/path-clients.png
      produces: 
        - application/json
      parameters:
        - $ref: "#/parameters/ClientId"
      responses:
        "200":
          description: Success
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: ../models/Client.yaml
        "401":
          description: Unauthorized or invalid token
        "404":
          description: Entity not found
        "500":
          description: Server error
  /{clientId}/interests:
    get:
      x-auth-type: "Application & Application User"
      x-scope: api_read
      x-throttling-tier: Unlimited
      summary: An array of Interests for the given clientId
      description:
        This process layer service queries the policy record keeping system, and returns an array of interests (relationships) between the client identified by the clientId and insurance objects.
      externalDocs:
        description: Interest Instance Diagram
        url: http://connections/issite/ews/SiteAssets/Client%20Model.png
      produces:
        - application/json
      parameters:
        - $ref: "#/parameters/ClientId" 
      responses:
        "200":
          description: Success
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: ../definitions.yaml#/definitions/Interest
        "404":
          description: Entity not found
parameters:
  ClientId:
    name: clientId
    required: true
    in: path
    description: The clientId used to identify the client which is the object of the request.
    type: string
definitions:
  Client:
    