swagger: "2.0"
info:
  version: 2.0.0
  title: clients
  description: |
    This is the entry point for client inquiries.

    #### Service Functionality:
    This API is called with a clientId parameter.  If successful, the resultant resource is a
    JSON oject, based on the Client model. 
    
    #### Performance Expectation:
    Standard SLA applies.
    
    #### Service Capacity Supported:
    Standard Capacity applies
    
    #### Suggested Test Scenario:
    TBD
    
    #### Service Availability:
    Standard Service Availability applies
    
    #### Service Security:
    HTTPS/SSL
produces:
  - application/json
schemes:
  - https
paths:
  /{clientId}:
    get:
      description: Returns a Client
      parameters:
        - name: clientId
          in: path
          description: The clientId
          required: true
          type: string
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: ../definitions.yaml#/definitions/Client
        "401":
          description: Unauthorized or invalid token
        "404":
          description: Entity not found
        "500":
          description: Server error