swagger: '2.0'
info:
  version: 1.0.0
  title: clients
  description: |
    This is the entry point for client inquiries against the client record-keeping system (Exceed).

    #### Service Functionality
    This API is called with a `clientId` parameter.  If found, the resultant resource is a JSON oject, based on the Client model.

    #### Diagrams
    ![Interaction](http://connections/issite/ews/SiteAssets/sd-client.png)
    ![Client](http://connections/issite/ews/SiteAssets/path-clients.png)

    #### Performance Expectation
    Standard SLA applies.
    
    #### Service Capacity Supported
    Standard Capacity applies
    
    #### Suggested Test Scenario
    TBD
    
    #### Service Availability
    Standard Service Availability applies
    
    #### Service Security
    HTTPS/SSL
  contact:
    name: Enterprise Web Services Team
    email: EWSDevelopers@infambureau.com
    url: http://connections/issite/ews/SitePages/Home.aspx
produces:
  - application/json
schemes:
  - http
  - https
host: ap-karafb-dev:8181
basePath: /api/clients
paths:
  /{clientId}:
    get:
      summary: Returns a array of Client models identified by the clientId
      description: |
        This process layer service queries the client record-keeping system (Exceed) using the submitted parameter (clientId).   A detailed Client is returned, if the clientId exists.
      produces: 
        - application/json
      parameters:
        - name: clientId
          required: true
          in: path
          description: The clientId used to identify the client in the record-keeping system.
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '../definitions.yaml#/definitions/Client'
        '401':
          description: Unauthorized or invalid token
        '404':
          description: Entity not found
        '500':
          description: Server error