swagger: "2.0"
info:
  version: 2.0.0
  title: Clients
  description: Clients endpoint
produces:
  - application/json
schemes:
  - https
basePath: /clients
paths:
  /{clientId}/:
    get:
      x-auth-type: "Application & Application User"
      x-scope: api_read
      x-throttling-tier: Unlimited
      description: Returns a Client
      parameters:
        - name: clientId
          in: path
          description: The clientId
          required: true
          type: string
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: ../definitions.yaml#/definitions/Client
        "401":
          description: Unauthorized or invalid token
        "404":
          description: Entity not found
        "500":
          description: Server error
  /{clientId}/interests:
    get:
      x-auth-type: "Application & Application User"
      x-scope: api_read
      x-throttling-tier: Unlimited
      summary: An array of Interest
      parameters:
        - $ref: "#/parameters/ClientId" 
      responses:
        "200":
          description: Success
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: ../definitions.yaml#/definitions/Interest
        "401":
          description: Unauthorized or invalid token
        "404":
          description: Entity not found
        "500":
          description: Server error
parameters:
  ClientId:
    name: clientId
    required: true
    in: path
    description: The clientId
    type: string