swagger: "2.0"
info:
  version: 2.0.0
  title: client-accounts
  description: |
    This is the entry point for client account inquiries.

    #### Service Functionality:
    This API is called with a client account number parameter.  If successful, the resultant resource is a
    JSON oject, based on the ClientAccount model. 
    
    #### Performance Expectation:
    Standard SLA applies.
    
    #### Service Capacity Supported:
    Standard Capacity applies
    
    #### Suggested Test Scenario:
    TBD
    
    #### Service Availability:
    Standard Service Availability applies
    
    #### Service Security:
    HTTPS/SSL
produces:
  - application/json
schemes:
  - https
basePath: /client-accounts
paths:
  /{clientAccountId}/:
    get:
      description: Returns a ClientAccount identified by the input parameter.
      parameters:
        - $ref: "#/parameters/ClientAccountId" 
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: ../models/ClientAccount.yaml
        "401":
          description: Unauthorized or invalid token
        "404":
          description: Entity not found
        "500":
          description: Server error
parameters:
  ClientAccountId:
    name: clientAccountId
    required: true
    in: path
    description: The client number as stored in the record keeping system.
    type: string