swagger: "2.0"
info:
  version: 1.0.0
  title: client-accounts
  description: |
    This is the entry point for client account inquiries against the record-keeping system.

    #### Service Functionality
    This API is called with a client account number (`clientAccountId`) parameter.  If found, the resultant resource is a JSON oject, based on the ClientAccount model. 
    
    #### Diagrams
    ![Interaction](http://connections/issite/ews/SiteAssets/sd-client-account%401%2d6.png)
    ![ClientAccount Model](http://connections/issite/ews/SiteAssets/ClientAccount%20Model.png)

    #### Performance Expectation
    Standard SLA applies.
    
    #### Service Capacity Supported
    Standard Capacity applies
    
    #### Suggested Test Scenario
    TBD
    
    #### Service Availability:
    Standard Service Availability applies
    
    #### Service Security
    HTTPS/SSL
  
  contact:
    name: Enterprise Web Services Team
    email: EWSDevelopers@infambureau.com
    url: http://connections/issite/ews/SitePages/Home.aspx
produces:
  - application/json
schemes:
  - http
  - https
paths:
  /{clientAccountId}:
    get:
      description: Returns a ClientAccount identified by the input parameter.
      parameters:
        - name: clientAccountId
          required: true
          in: path
          description: The client number as stored in the record-keeping system.
          type: string   
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: ../models/ClientAccount.yaml
        "401":
          description: Unauthorized or invalid token
        "404":
          description: Entity not found
        "500":
          description: Server error