swagger: '2.0'
info:
  version: 1.0.0
  title: client-search
  description: |
    A [system](http://connections/issite/iCAF/SitePages/Home.aspx) layer API which searches the client record-keeping system for a collection of clients which match some combination of:

    * First Name
    * Last Name
    * Date of Birth
    * Tax ID (SSN)

    #### Service Functionality
    This service sit between the process and system layers (see [here](http://connections/issite/iCAF/SitePages/Home.aspx) for a description of this architecture).

    #### Diagrams
    ![Interaction](http://connections/issite/EWS/SiteAssets/sd-client-search%401-6.png)
    Request JSON:
    ![Request](http://connections/issite/ews/SiteAssets/schema-client-search-request.png)
    ![Client](http://connections/issite/EWS/SiteAssets/Client%20Model.png)
    #### Known Implementations
    * Life Death Claims (LDC)
    
    The following demographic information combinations are supported:
    
    * Last Name
    * Last Name, First Name
    * Last Name, Date of Birth
    * Tax Id
    
    #### Performance Expectation
    Standard SLA applies.
    
    #### Service Capacity Supported
    Standard Capacity applies
    
    #### Suggested Test Scenario
    TBD
    
    #### Service Availability
    Standard Service Availability applies
    
    #### Service Security
    HTTPS/SSL
  contact:
    name: Enterprise Web Services Team
    email: EWSDevelopers@infambureau.com
    url: http://connections/issite/ews/SitePages/Home.aspx
schemes:
  - 'http'
  - 'https'
consumes:
  - 'application/json'
produces:
  - 'application/json'
host: ap-karafb-dev:8181
basePath:
  /api
paths:
  /client-search:
    post:
      summary:  Search client records
      description: |
        Seaches the client record-keeping system for records matching the request parameters.
      parameters:
        - name:  client-search-request
          in: body
          description: The input paramters in JSON format
          required: true
          schema:
            $ref: '../definitions.yaml#/definitions/client-search-request'
      responses:
        '200':
          description: |
            Success.  A collection of one or more clients is returned.
          schema:
            type: array
            items:
              $ref: '../definitions.yaml#/definitions/Client'
        default:
          description: |
            Failure.
