swagger: '2.0'
info:
  version: 1.0.0
  title: client-search
  x-architectural-layer: system
  description: |
    A system layer API which searches the client record-keeping system for a collection of clients which match some combination of:

    * First Name
    * Last Name
    * Date of Birth
    * Tax ID (SSN)

    #### Service Functionality
    This service layer service is used to find client objects which match the criteria present in the service request (a POST payload). 

    #### Diagrams
    ![Interaction](http://connections/issite/EWS/SiteAssets/sd-client-search-1.0.0.png)
    
    #### Known Implementations
    **Life Death Claims (LDC)**
    
    The following demographic information combinations are supported:
    
    * Last Name
    * Last Name, First Name
    * Last Name, Date of Birth
    * Tax Id
    
    #### Performance Expectation
    Standard SLA applies.
    
    #### Service Capacity Supported
    Standard Capacity applies
    
    #### Suggested Test Scenario
    TBD
    
    #### Service Availability
    Standard Service Availability applies
    
    #### Service Security
    HTTPS/SSL
  contact:
    name: Enterprise Web Services Team
    email: EWSDevelopers@infambureau.com
    url: http://connections/issite/ews/SitePages/Home.aspx
schemes:
  - 'http'
  - 'https'
consumes:
  - 'application/json'
produces:
  - 'application/json'
paths:
  /:
    post:
      summary:  Search client records
      description: |
        Seaches the client record-keeping system for records matching the request parameters.
      parameters:
        - name:  client-search-request
          in: body
          description: The input paramters in JSON format
          required: true
          schema:
            $ref: '../definitions.yaml#/definitions/client-search-request'
      responses:
        '200':
          description: |
            Success.  A collection of one or more clients is returned.
          schema:
            type: array
            items:
              $ref: '../definitions.yaml#/definitions/Client'
          examples:
            application/json:
              $ref: '../definitions.yaml#/definitions/client-search-1.0.0-post-response'
        default:
          description: |
            Failure.