swagger: "2.0"
info:
  version: 2.0.0
  title: Client_Accounts
  description: Client Accounts endpoint
produces:
  - application/json
schemes:
  - https
basePath: /client-accounts
paths:
  /{clientAccountId}/:
    get:
      description: Returns a ClientAccount
      parameters:
        - $ref: "#/parameters/ClientAccountId" 
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: ../definitions.yaml#/definitions/ClientAccount
        "401":
          description: Unauthorized or invalid token
        "404":
          description: Entity not found
        "500":
          description: Server error
parameters:
  ClientAccountId:
    name: clientAccountId
    required: true
    in: path
    description: The clientAccountId
    type: string