swagger: "2.0"
info:
  version: 1.0.0
  title: codes
  description: |
    This is a system layer sevice which exposes an enterprise service to map between system codes and a common code topology.

    #### Service Functionality
    This API is called with several possible combinations of codes (system/common) and returns a standard JSON response structure which represents the mapping to other related information in the system mapping store.

    #### Sequence Diagram
    ![Mapping](http://connections/issite/ews/SiteAssets/sd-codes.png)

    #### Performance Expectation
    Standard SLA applies.
    
    #### Service Capacity Supported
    Standard Capacity applies
    
    #### Suggested Test Scenario
    TBD
    
    #### Service Availability
    Standard Service Availability applies
    
    #### Service Security
    HTTPS/SSL
  contact:
    name: Enterprise Web Services Team
    url: http://connections/issite/ews/SitePages/Home.aspx
    email: ewsdevelopers@infarmbureau.com
produces:
  - application/json
schemes:
  - http
  - https
host:
  ap-karafb-dev:8181
basePath:
  /api/codes
paths:
  /:
    get:
      summary: map known code values to common structure
      description: |
        given known facts for a code, return the standard structure for mapping codes.
      parameters:
        - name: systemCode
          in: query
          description:  The system for with the code to be mapped.
          required:  true
          type: string
        - name: commonCodeName
          in: query
          description: The name for the code as defined for the enterprise code mapping.
          required: true
          type: string
        - name: systemCodeValue
          in: query
          description: |
            The value of the system code to be mapped.  Either `systemCodeValue` or `commonCodeValue` is required to complete the mapping key.
          required: false
          type: string
        - name: commonCodeValue
          in: query
          description: |
            The value of the common code to be mapped. Either `systemCodeValue` or `commonCodeValue` is required to complete the mapping key. 
          required: false
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: ../definitions.yaml#/definitions/codes-response
        '404':
          description: Not Found
        '500':
          description: Server Error