swagger: '2.0'
info:
  version: 1.0.0
  title: documents
  x-architectural-layer: system
  description: |
    A [system](http://connections/issite/iCAF/SitePages/APIs%20-%20System%20vs%20Process%20vs%20Experience.aspx) layer API.

    #### Service Functionality
    This service performs two task.
    * Generate a document using the SmartCommunication cloud service.

    #### Sequence Diagram
    ![Interaction](http://connections/issite/ews/SiteAssets/api.sytem.documents-design.png)

    #### Known Implementations
    * Care+ Review

    #### Performance Expectation
    Standard SLA applies.
    
    #### Service Capacity Supported
    Standard Capacity applies
    
    #### Suggested Test Scenario
    TBD
    
    #### Service Availability
    Standard Service Availability applies
    
    #### Service Security
    HTTPS/SSL
  contact:
    name: Enterprise Web Services Team
    email: EWSDevelopers@infambureau.com
    url: http://connections/issite/ews/SitePages/Home.aspx
schemes:
  - 'https'
  - 'http'
consumes:
  - 'application/json'
produces:
  - 'application/json'
host:
  ap-karafb-dev:8181
basePath:
  /api/documents
paths:
  /:
    post:
      summary:  Generate document
      description: |
        Generate document with Smart Communication cloud services.
      parameters:
        - name:  documents-request
          in: body
          description: The input paramters in JSON format
          required: true
          schema:
            $ref: '../definitions.yaml#/definitions/documents-request'
        - name: includeDocumentData
          in: query
          description: includeDocumentData=true will return the generated document in the response payload under document.content .
          required: false
          type: boolean
      responses:
        '200':
          description: |
            Success. Generated document with Smart Communication cloud services.
          schema:
            $ref: '../definitions.yaml#/definitions/documents-response'
        default:
          description: |
            Failure.
    get:
      summary:  Get cached document
      description: |
        Get cached document with Smart Communication cloud services.
      parameters:
        - name: cachedDocumentLocation
          in: query
          description: |
            cachedDocumentLocation will contain the partial uri provided by Smart Communication on invocation
            of the POST.
          required: true
          type: string
      produces:
        - 'application/pdf'
      responses:
        '200':
          description: |
            returns the pdf content
          schema:
            type: file
        default:
          description: |
            Failure.