swagger: '2.0'
info:
  version: '1.0.0'
  title: enterprise-pers-auto-services
  description: |
    This API is used to initiate a transfer of automobile insurance coverage from one vehicle to another.  It is intended to provide system and process layer (See [here](http://connections/issite/iCAF/SitePages/Home.aspx) for a description of this architecure) access to a self service front end.

    This service is built using the Simple Object Access Protocol (SOAP).

    #### Service Functionality
    Using the Exceed COM framework, this service orchestrates the necessary calls to the record-keeping system, wrapping th ACORD transactions as necessary.  This exposes the same functionality used by the CSR to effect a change in the covered vehicle.

    ![Vehicle Transfer](http://connections/issite/ews/SiteAssets/sd-Vehicle%20Transfer%20Overview.png)

    #### Known Implementations
    
    _Vehicle Transfer_

    [Sample Request XML](http://connections/issite/ews/SiteAssets/VehicleTransfer_And_VehicleQuestionsChange.xml)

    #### Performance Expectation
    TBD

    #### Service Capacity Supported
    TBD

    #### Suggested Test Scenario
    TODO:  Get with Scott on this

    #### Service Availability
    TBD

    #### Service Security
    TBD

  contact:
    name: Enterprise Web Services 
    email: ewsdevelopers@infarmbureau.com
    url: http://connections/issite/ews/SitePages/Home.aspx

basePath: /camel
schemes:
  - http
  - https
consumes:
  - application/xml
produces:
  - application/xml
paths:
  /PolicyMod:
    post:
      tags:
        - 'PolicyMod'
        - 'Policy'
      summary:  Modifies an auto policy.
      description: Used to transfer an auto policy from one vehicle to another
      operationId: JavaMethodName
      consumes:
        - application/xml
      produces:
        - application/xml
      parameters:
        - name: PolicyModInXML
          in:  body
          description: The SOAP XML Request body.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The SOAP XML Response body.
          schema:
            type: file
  /PolicyChangeLimit:
    post:
      tags:
        - 'PolicyChangeLimit'
        - 'Policy'
      summary: Changes one or more limits
      description: Based on some business logic, this changes limits when applicable
      operationId:  JavaMethodName1
      consumes:
        - application/xml
      produces:
        - applicaiton/xml
      responses:
        '200':
          description: coverage change response
          schema:
            type: file
      
