swagger: '2.0'
info:
  version: '1.0.0'
  title: pc-persautopolicymod
  description: |
    This API is used to initiate a transfer of automobile insurance coverage from one vehicle to another.  It is intended to provide process layer access (See [here](http://connections/issite/iCAF/SitePages/Home.aspx) for a description of this architecure) to a self service front end.  The API has been designed to be a framework which is reusable, allowing future personal automobile insurance transactions to be added.

    #### Service Functionality
    This service is built on top of the existing Exceed COM framework.  This framework is deployed on the Enterprise Service Bus (ESB); the framework provides a layer of abstraction which exposes the Exceed application via an external API.

    Using the Exceed COM framework, this service orchestrates the necessary calls to the record-keeping system, wrapping the ACORD transactions as necessary.  This exposes the same functionality, to effect a change in the vehicle policy, as would be available to a Customer Service Representative via the exceed application.

    ![Vehicle Transfer](http://connections/issite/ews/SiteAssets/sd-Vehicle%20Transfer%20Overview.png)

    #### Known Implementations
    
    _Vehicle Transfer_
    ####TODO move samples 
    [Sample Request XML](http://connections/issite/ews/SiteAssets/VehicleTransfer_And_VehicleQuestionsChange.xml)

    #### Performance Expectation
    TBD

    #### Service Capacity Supported
    TBD

    #### Suggested Test Scenario
    TODO:  Get with Scott on this

    #### Service Availability
    TBD

    #### Service Security
    TBD

  contact:
    name: Enterprise Web Services 
    email: ewsdevelopers@infarmbureau.com
    url: http://connections/issite/ews/SitePages/Home.aspx

basePath: /camel
schemes:
  - http
  - https
consumes:
  - application/xml
produces:
  - application/xml
paths:
  /PolicyMod:
    post:
      tags:
        - 'PolicyMod'
        - 'Policy'
      summary:  Modifies an auto policy.
      description: Used to transfer an auto policy from one vehicle to another
      operationId: JavaMethodName
      consumes:
        - application/xml
      produces:
        - application/xml
      parameters:
        - name: PolicyModInXML
          in:  body
          description: The SOAP XML Request body.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The SOAP XML Response body.
          schema:
            type: file
  /PolicyChangeLimit:
    post:
      tags:
        - 'PolicyChangeLimit'
        - 'Policy'
      summary: Changes one or more limits
      description: Based on some business logic, this changes limits when applicable
      operationId:  JavaMethodName1
      consumes:
        - application/xml
      produces:
        - applicaiton/xml
      responses:
        '200':
          description: coverage change response
          schema:
            type: file
      
