swagger: '2.0'
info:
  version: '1.0.0'
  title: pc-persautopolicymod
  description: |
    This API is used to initiate a transfer of automobile insurance coverage from one vehicle to another.  It is intended to provide process layer access (See [here](http://connections/issite/iCAF/SitePages/Home.aspx) for a description of this architecure) to a self service front end.  The API has been designed to be a framework which is reusable, allowing future personal automobile insurance transactions to be added.

    #### Service Functionality
    This service is built on top of the existing Exceed COM framework and the Enterprise Service Bus (ESB).  This framework is deployed on the Enterprise Service Bus (ESB); the framework provides a layer of abstraction which exposes the Exceed application via an external API.

    Using the Exceed COM framework, this service orchestrates the necessary calls to the record-keeping system, wrapping the ACORD transactions as necessary.  This exposes the same functionality, to effect a change in the vehicle policy, as would be available to a Customer Service Representative via the exceed application.

    ![Vehicle Transfer](http://connections/issite/ews/SiteAssets/sd-pc-persautotransfer.png)

    #### Known Implementations
    _Vehicle Transfer_
    
    #### Example XML
    | Requests | Responses |
    | --- | ---|
    | [Free Form Vehicle Info](http://connections/issite/ews/SiteAssets/pc-persautotransfer/requests/Has_FreeformEnteredVehicleInfo.xml) | [Has Vehicle Questions Change](http://connections/issite/ews/SiteAssets/pc-persautotransfer/requests/Has_VehicleQuestionsChange_NO.xml) |
    | [Has Vehicle Coverge Change](http://connections/issite/ews/SiteAssets/pc-persautotransfer/requests/Has_VehicleCoverageChange.xml) | |
    | [Has Vehicle Interest Change](http://connections/issite/ews/SiteAssets/pc-persautotransfer/requests/Has_VehicleInterestsChange.xml) | |
    | [Has Vehicle Questions Change NO](http://connections/issite/ews/SiteAssets/pc-persautotransfer/requests/Has_VehicleQuestionsChange_NO.xml) | |
    | [Has Vehicle Questions Change YES](http://connections/issite/ews/SiteAssets/pc-persautotransfer/requests/Has_VehicleQuestionsChange_YES.xml) | |
    
        
    #### Performance Expectation
    TBD

    #### Service Capacity Supported
    TBD

    #### Suggested Test Scenario
    TODO:  Get with Scott on this

    #### Service Availability
    TBD

    #### Service Security
    TBD

  contact:
    name: Enterprise Web Services 
    email: ewsdevelopers@infarmbureau.com
    url: http://connections/issite/ews/SitePages/Home.aspx

basePath: /camel
schemes:
  - http
  - https
consumes:
  - application/xml
produces:
  - application/xml
paths:
  /:
    post:
      summary:  SOAP Call to ESB
      description: |
        Exposes a SOAP endpoint for clients to request a vehicle transfer
      consumes:
        - application/xml
      produces:
        - application/xml
      parameters:
        - name: PolicyModInXML
          in:  body
          description: The SOAP XML Request body.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The SOAP XML Response body.
          schema:
            type: file