swagger: '2.0'
info:
  version: 1.0.0
  title: generate-document
  description: |
    A [process](http://connections/issite/iCAF/SitePages/APIs%20-%20System%20vs%20Process%20vs%20Experience.aspx) layer API.

    #### Service Functionality
    This service performs two task.
    * Generate a document based of generateConfiguration via api.system.documents.
    * Archive the generated document based of archiveConfiguration via api.system.archive.

    #### Diagrams

    Request JSON:

    #### Known Implementations
    * Care+ Review

    #### Performance Expectation
    Standard SLA applies.
    
    #### Service Capacity Supported
    Standard Capacity applies
    
    #### Suggested Test Scenario
    TBD
    
    #### Service Availability
    Standard Service Availability applies
    
    #### Service Security
    HTTPS/SSL
  contact:
    name: Enterprise Web Services Team
    email: EWSDevelopers@infambureau.com
    url: http://connections/issite/ews/SitePages/Home.aspx
schemes:
  - 'https'
  - 'http'
consumes:
  - 'application/json'
produces:
  - 'application/json'
paths:
  /:
    post:
      summary:  Generate and archive document
      description: |
        Generate and archive document.
      parameters:
        - name:  generate-document-request
          in: body
          description: The input paramters in JSON format
          required: true
          schema:
            $ref: '../definitions.yaml#/definitions/generate-document-request'
      responses:
        '201':
          description: |
            Created.  No content is returned.
        default:
          description: |
            Failure.
