swagger: "2.0"
info:
  version: 1.0.0
  title: individual-addresses
  x-architectural-layer: process
  description: |
    This is the entry point for obtaining all addresses associated with an individual

    #### Service Functionality
    This API is called with a 'clientId' parameter.  If found, the resultant resource is a collection of Address models in JSON form.

    #### Diagrams
    ![Interaction](http://connections/issite/ews/SiteAssets/api.process.individual-addresses-design.png)

    #### Performance Expectation
    Standard SLA applies.

    #### Service Capacity Supported
    Standard Capacity applies

    #### Suggested Test Scenario
    TBD

    #### Service Availability:
    Standard Service Availability applies

    #### Service Security
    HTTPS/SSL

  contact:
    name: Enterprise Web Services Team
    email: EWSDevelopers@infambureau.com
    url: http://connections/issite/ews/SitePages/Home.aspx
produces:
  - application/json
schemes:
  - http
  - https
host:
  ap-karafb-dev:8181
basePath:
  /api/client/individual
paths:
  /{clientId}/addresses:
    get:
      description: Returns an array of Addresses identified by the input parameter.
      parameters:
        - name: clientId
          required: true
          in: path
          description: The clientId of the Individual as stored in the record-keeping system.
          type: string
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: ../models/Address.yaml
        "401":
          description: Unauthorized or invalid token
        "404":
          description: Entity not found
        "500":
          description: Server error