swagger: "2.0"
info:
  version: 2.0.0
  title: Memberships
  description: |
    This is the entry point for membership inquiries.

    #### Service Functionality:
    This API is called with a membershipId parameter.  If successful, the resultant resource is a
    JSON oject, based on the Membership model. 
    
    #### Performance Expectation:
    Standard SLA applies.
    
    #### Service Capacity Supported:
    Standard Capacity applies
    
    #### Suggested Test Scenario:
    TBD
    
    #### Service Availability:
    Standard Service Availability applies
    
    #### Service Security:
    HTTPS/SSL
produces:
  - application/json
schemes:
  - https
basePath: /memberships
paths:
  /{membershipId}/:
    get:
      x-auth-type: "Application & Application User"
      x-scope: api_read
      x-throttling-tier: Unlimited
      description: Returns a Membership
      parameters:
        - $ref: "#/parameters/MembershipId"
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: ../models/Membership.yaml
        "401":
          description: Unauthorized or invalid token
        "404":
          description: Entity not found
        "500":
          description: Server error
parameters:
  MembershipId:
    name: membershipId
    required: true
    in: path
    description: The membershipId or membership number 
    type: string    