swagger: "2.0"
info:
  version: 1.0.0
  title: memberships
  x-architectural-layer: process
  description: |
    A [process](http://connections/issite/iCAF/SitePages/Home.aspx) layer API which exposes membership inquiries against the record-keeping system.

    #### Service Functionality
    This API is called with a `membershipId` parameter.  If successful, the resultant resource is a JSON oject, based on the Membership model.

    #### Diagrams
    ![Interaction](http://connections/issite/ews/SiteAssets/sd-membership%401-6.png)
    ![Membership](http://connections/issite/ews/SiteAssets/Membership%20Model.png)

    #### Performance Expectation
    Standard SLA applies.
    
    #### Service Capacity Supported
    Standard Capacity applies
    
    #### Suggested Test Scenario
    TBD
    
    #### Service Availability
    Standard Service Availability applies
    
    #### Service Security
    HTTPS/SSL
  contact:
    name: Enterprise Web Services Team
    email: EWSDevelopers@infambureau.com
    url: http://connections/issite/ews/SitePages/Home.aspx
produces:
  - application/json
schemes:
  - http
  - https
paths:
  /{membershipId}:
    get:
      description: Returns a Membership
      parameters:
        - name: membershipId
          required: true
          in: path
          description: The membership number in the record-keeping system. 
          type: string 
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: ../definitions.yaml#/definitions/Membership
          examples:
            application/json:
              $ref: ../definitions.yaml#/definitions/memberships-1.0.0-get-response
        "401":
          description: Unauthorized or invalid token
        "404":
          description: Entity not found
        "500":
          description: Server error