swagger: "2.0"
info:
  version: 2.0.0
  title: Policies
  description: Policy Endpoints
produces:
  - application/json
schemes:
  - https
basePath: /policies
paths:
  /{policyId}:
    get:
      summary: a Policy
      parameters:
        - $ref: "#/parameters/PolicyId"
      responses:
        "200":
          description: Success
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: ../definitions.yaml#/definitions/Policy
        "401":
          description: Unauthorized or invalid token
        "404":
          description: Entity not found
        "500":
          description: Server error                  
  /{policyId}/interests:
    get:
      summary: An array of Interest
      parameters:
        - $ref: "#/parameters/PolicyId"
      responses:
        "200":
          description: Success
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: ../definitions.yaml#/definitions/Interest
        "401":
          description: Unauthorized or invalid token
        "404":
          description: Entity not found
        "500":
          description: Server error                  
parameters:
  PolicyId:
    name: policyId
    required: true
    in: path
    description: policyId
    type: string