swagger: '2.0'
info:
  version: 1.0.0
  title: testa-policies
  x-architectural-layer: system
  description: |
    This is a test yaml file for creating WS02 Store api.  It has two paths.
    
    ### Service Functionality
    This service does nothing.

  contact:  
    name:  Mary Boscaccia
    url:  http://www.infarmbureau.com
    email: mary.Boscacci@infarmbureau.com
produces:
  - application/json
schemes:
  - http
  - https
host:
  ap-karafb-dev:8181
basePath:
  /api/policies/test-policies
paths:
  /{dummyId}:
    get:
      summary: Does nothing
      description: |
        This API is for testing of the store only
      parameters:
        - name: dummyId
          required: true
          in: path
          description: The dummy identifer
          type: string
      responses:
        '200':
          description: |
            Success
          schema:
            type: object
            properties:
              data:
                type: string
        '401':
          description: Unauthorized or invalid token
        '404':
          description: Entity not found
        '500':
          description: Server error
  /{dummyId}/another-path:
    get:
      summary: Still doesn't do anything
      description: |
        This API path is for addtional testing
      parameters:
        - name: dummyId
          required: true
          in: path
          description: The dummy identifer
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              data:
                type: string
          examples:
            application/json:
              $ref: '../definitions.yaml#/definitions/testa-example-response'
        '401':
          description: Unauthorized or invalid token
        '404':
          description: Entity not found
        '500':
          description: Server error
    delete:
      summary: doesn't delete anything
      description: |
        This API path is for ymt.
      parameters:
        - name: dummyId
          required: true
          in: path
          description: The dummy identifier
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              data:
                type: string
        '500':
          description: Server Error

                