swagger: '2.0'
info:
  version: 1.0.0
  title: telematics
  x-architectural-layer: system
  description: |
    A [system](http://connections/issite/iCAF/SitePages/APIs%20-%20System%20vs%20Process%20vs%20Experience.aspx) layer API.

    #### Service Functionality
    This service allows various CRUD operations with the Lexis Nexis telematics webservices. It allows creation, retrival, and
    deletion of household, policy, and driver. Only update allowed is for driver.

    **Warning** the deletion of an entitiy has cascading affect. For example, a household with one policy and one driver
    under that policy, if the driver is deleted then it automatically
    deletes the parent policy and houeshold.

    #### Known Implementations
    Exceed Auto Policy Telematics service

    #### Performance Expectation
    Standard SLA applies.
    
    #### Service Capacity Supported
    Standard Capacity applies
    
    #### Suggested Test Scenario
    TBD
    
    #### Service Availability
    Standard Service Availability applies
    
    #### Service Security
    HTTPS/SSL
  contact:
    name: Enterprise Web Services Team
    email: EWSDevelopers@infambureau.com
    url: http://connections/issite/ews/SitePages/Home.aspx
schemes:
  - 'https'
  - 'http'
consumes:
  - 'application/json'
  - 'application/xml'
produces:
  - 'application/json'
  - 'application/xml'
basePath:
  /api/telematics
paths:
  /household:
    post:
      summary:  Creates a household with household, policy and driver data.
      description: |
        Creates a household with policy and driver data in the Lexis Nexis telematics system.
      parameters:
        - name: telematics-household-request
          in: body
          description: The input paramters in JSON format.
          required: true
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
        - $ref: '#/parameters/Content-Type'
        - $ref: '#/parameters/Accept'
      responses:
        '201':
          description: |
            Successful creation of household.
        '400':
          description: |
            Invalid payload.
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
                  properties:
                    errorMessage:
                      type: string
          examples:
            application/json:
              $ref: ../examples/telematics-1.0.0-add-household-response-error.json
        '500':
          description: |
            Server error.
  /household/{householdId}:
    get:
      description: Returns a Household.
      parameters:
        - $ref: '#/parameters/householdId'
        - $ref: '#/parameters/Accept'
      responses:
        '200':
          description: Successful response.
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
          examples:
            application/json:
              $ref: ../examples/telematics-1.0.0-get-household-response.json
            application/xml:
              $ref: ../examples/telematics-1.0.0-get-household-response.xml
        '404':
          description: |
            Resource does not exist.
        '500':
          description: |
            Server error.
    delete:
      description: Delete a Household.
      parameters:
        - $ref: '#/parameters/householdId'
      responses:
        '200':
          description: Successful deletion of the household.
        '500':
          description: Failure.

  /household/{householdId}/policy:
    post:
      summary:  Creates a policy with policy and driver data.
      description: |
        Creates a policy with policy and driver data for a household in the Lexis Nexis telematics system.
      parameters:
        - $ref: '#/parameters/householdId'
        - name: telematics-policy-request
          in: body
          description: The input paramters in JSON format
          required: true
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
        - $ref: '#/parameters/Content-Type'
        - $ref: '#/parameters/Accept'
      responses:
        '201':
          description: |
            Success creation of policy.
        '400':
          description: |
            Invalid payload.
        '500':
          description: |
            Server error.
  /household/{householdId}/policy/{policyId}:
    get:
      description: Returns a policy
      parameters:
        - $ref: '#/parameters/householdId'
        - $ref: '#/parameters/policyId'
        - $ref: '#/parameters/Accept'
      responses:
        '200':
          description: Successful response.
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
          examples:
            application/json:
              $ref: ../examples/telematics-1.0.0-get-policy-response.json
            application/xml:
              $ref: ../examples/telematics-1.0.0-get-policy-response.xml
        '404':
          description: |
            Resource does not exist.
        '500':
          description: |
            Server error.
    delete:
      description: Delete a policy.
      parameters:
        - $ref: '#/parameters/householdId'
        - $ref: '#/parameters/policyId'
      responses:
        '200':
          description: Successful deletion of the policy.
        '500':
          description: Failure.

  /household/{householdId}/policy/{policyId}/driver:
    post:
      summary:  Creates a driver for a household and policy.
      description: |
        Creates a driver for a household and policy in the Lexis Nexis telematics system.
      parameters:
        - $ref: '#/parameters/householdId'
        - $ref: '#/parameters/policyId'
        - name: telematics-driver-request
          in: body
          description: The input paramters in JSON format.
          required: true
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
        - $ref: '#/parameters/Content-Type'
        - $ref: '#/parameters/Accept'
      responses:
        '201':
          description: |
            Success creation of driver.
        '400':
          description: |
            Invalid payload.
        '500':
          description: |
            Server error.
    put:
      summary:  Update a driver for a household and policy.
      description: |
        Update a driver for a household and policy in the Lexis Nexis telematics system.
      parameters:
        - $ref: '#/parameters/householdId'
        - $ref: '#/parameters/policyId'
        - name: telematics-driver-request
          in: body
          description: The input paramters in JSON format.
          required: true
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
        - $ref: '#/parameters/Content-Type'
        - $ref: '#/parameters/Accept'
      responses:
        '201':
          description: |
            Success creation of household.
        '400':
          description: |
            Invalid payload.
        '500':
          description: |
            Server error.
  /household/{householdId}/policy/{policyId}/driver/{driverId}:
    get:
      description: Returns a driver
      parameters:
        - $ref: '#/parameters/householdId'
        - $ref: '#/parameters/policyId'
        - $ref: '#/parameters/driverId'
        - $ref: '#/parameters/Accept'
      responses:
        '200':
          description: Successful response.
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
          examples:
            application/json:
              $ref: ../examples/telematics-1.0.0-get-policy-response.json
            application/xml:
              $ref: ../examples/telematics-1.0.0-get-policy-response.xml
        '404':
          description: |
            Resource does not exist.
        '500':
          description: |
            Server error.
    delete:
      description: Delete a driver.
      parameters:
        - $ref: '#/parameters/householdId'
        - $ref: '#/parameters/policyId'
        - $ref: '#/parameters/driverId'
      responses:
        '200':
          description: Successful deletion of the policy.
        '500':
          description: Failure.

parameters:
  householdId:
    name: householdId
    required: true
    in: path
    description: The household id for Lexis Nexis.
    type: string
  policyId:
    name: policyId
    required: true
    in: path
    description: The policy id for Lexis Nexis.
    type: string
  driverId:
    name: driverId
    required: true
    in: path
    description: The driver id for Lexis Nexis.
    type: string
  Content-Type:
    name: Content-Type
    in: header
    description: Determines the request format. Allowed values are 'appliation/json' or 'application/xml'.
    required: false
    type: string
  Accept:
    name: Accept
    in: header
    description: Determines the response format. Allowed values are 'appliation/json' or 'application/xml'.
    required: false
    type: string
