swagger: '2.0'
info: {version: 2.0.0, title: client-accounts, description: "This is the entry point\
    \ for client account inquiries.\n\n#### Service Functionality:\nThis API is called\
    \ with a client account number parameter.  If successful, the resultant resource\
    \ is a\nJSON oject, based on the ClientAccount model. \n\n#### Performance Expectation:\n\
    Standard SLA applies.\n\n#### Service Capacity Supported:\nStandard Capacity applies\n\
    \n#### Suggested Test Scenario:\nTBD\n\n#### Service Availability:\nStandard Service\
    \ Availability applies\n\n#### Service Security:\nHTTPS/SSL\n"}
produces: [application/json]
schemes: [https]
basePath: /client-accounts
paths:
  /{clientAccountId}/:
    get:
      description: Returns a ClientAccount identified by the input parameter.
      parameters:
      - &id0001 {name: clientAccountId, required: true, in: path, description: The
          client number as stored in the record keeping system., type: string}
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  description: A Client Account model
                  required: [id, accountNumber, accountName, contactName, address,
                    phoneNumber, agentId, agentName, relatedClients]
                  properties:
                    id: {description: The unique identifier for the ClientAccount,
                      type: string}
                    accountNumber: {description: The Client Account number that is
                        displayed., type: string}
                    accountName: {description: 'The name given to the account by the
                        client.

                        Defaults to the head of household''s last name.

                        ', type: string}
                    contactName:
                      description: 'Name of the primary contact for the Client Account.

                        Defaults to the "Head of Household" Client.

                        '
                      type: [string, 'null']
                    address:
                      description: "Address model--used with various parent objects\
                        \ to describe the US Postal Service\nlocation. \n"
                      required: [addressType, addressAggregate, street1, street2,
                        city, state, countyCode, county, townshipCode, township, postalCode,
                        country]
                      properties:
                        addressType:
                          description: 'Future use.  If used, SHOULD be set to ''Mailing''.

                            '
                          type: [string]
                          enum: [Mailing]
                        addressAggregate:
                          description: 'The aggregate address for use when the individual
                            components are not known.

                            '
                          type: [string, 'null']
                        street1:
                          description: 'First line of the postal address, e.g. 100
                            Main St.

                            '
                          type: [string, 'null']
                        street2:
                          description: 'Second line of the postal address, e.g. Unit
                            100.

                            '
                          type: [string, 'null']
                        city:
                          type: [string, 'null']
                        state:
                          description: 'For domestic addresses, use USPS two-digit
                            state code.

                            '
                          type: [string, 'null']
                        countyCode:
                          description: 'Properties countyCode and county are mutually
                            exclusive.  Use countyCode when the source system provides
                            a two-character code.  If the source is the actual County
                            name, then use the county property.

                            '
                          type: [string, 'null']
                        county:
                          description: 'Properties countyCode and county are mutually
                            exclusive.  Use countyCode when the source system provides
                            a two-character code.  If the source is the actual County
                            name, then use the county property.

                            '
                          type: [string, 'null']
                        townshipCode:
                          description: 'Properties townshipCode and township are mutually
                            exclusive.  Use townshipCode when the source system provides
                            a two-character code.  If the source is the actual Township
                            name, then use the township property.

                            '
                          type: [string, 'null']
                        township:
                          description: 'Properties townshipCode and township are mutually
                            exclusive.  Use townshipCode when the source system provides
                            a two-character code.  If the source is the actual Township
                            name, then use the township property.

                            '
                          type: [string, 'null']
                        postalCode:
                          description: 'The USPS postal code, also known as the zip
                            code.  Should be in the format ##### or #####-#### (zip
                            plus four).

                            '
                          type: [string, 'null']
                        country:
                          description: 'The name of the country.

                            '
                          type: [string, 'null']
                    phoneNumber:
                      description: Phone model
                      properties:
                        phoneNumber: {description: 'The phone number in the ITU-T
                            E.164.1 Format,

                            ', type: string, format: e.164.1}
                        phoneType:
                          description: 'These enumerations are sourced from Exceed
                            Client

                            '
                          enum: [Alternate, Business, Contact, Emergency, Fax, Account,
                            Home, Vacation, Work, Cell, Pager, Relative, Toll Free,
                            Unlisted]
                        phoneTypeCode: {type: string}
                    agentId:
                      description: 'The id of the agent associated with the account.

                        '
                      type: [string]
                    agentName:
                      type: [string]
                    relatedClients:
                      description: 'Array of objects containing relatedClients associated
                        to ClientAccount

                        '
                      type: array
                      items:
                        type: object
                        properties:
                          clientId:
                            type: [string]
                          clientAccountRelationship:
                            type: [string]
                          clientAccountRelationshipCode:
                            type: [string]
        '401': {description: Unauthorized or invalid token}
        '404': {description: Entity not found}
        '500': {description: Server error}
parameters:
  ClientAccountId: *id0001
