swagger: '2.0'
info:
  version: 1.0.0
  title: enterprise-pers-auto-services
  description: 'This API is used to initiate a transfer of automobile insurance coverage
    from one vehicle to another.  It is intended to provide system and process layer
    (See [here](http://connections/issite/iCAF/SitePages/Home.aspx) for a description
    of this architecure) access to a self service front end.


    This service is built using the Simple Object Access Protocol (SOAP).


    #### Service Functionality

    Using the Exceed COM framework, this service orchestrates the necessary calls
    to the record-keeping system, wrapping th ACORD transactions as necessary.  This
    exposes the same functionality used by the CSR to effect a change in the covered
    vehicle.


    ![Vehicle Transfer](http://connections/issite/ews/SiteAssets/sd-Vehicle%20Transfer%20Overview.png)


    #### Performance Expectation

    TBD


    #### Service Capacity Supported

    TBD


    #### Suggested Test Scenario

    TODO:  Get with Scott on this


    #### Service Availability

    TBD


    #### Service Security

    TBD

    '
  contact: {name: Enterprise Web Services, email: ewsdevelopers@infarmbureau.com,
    url: 'http://connections/issite/ews/SitePages/Home.aspx'}
basePath: /camel
schemes: [http, https]
consumes: [application/xml]
produces: [application/xml]
paths:
  /PolicyMod:
    post:
      tags: [PolicyMod, Policy]
      summary: Modifies an auto policy.
      description: Used to transfer an auto policy from one vehicle to another
      operationId: JavaMethodName
      consumes: [application/xml]
      produces: [application/xml]
      responses:
        '200':
          description: modification response
          schema: {type: file}
          examples: {application/xml: '<ACORD xmlns="http://www.ACORD.org/standards/PC_Surety/ACORD1/xml/">
              <SignonRs> <ClientDt>2016-11-08T12:08:56.235-05:00</ClientDt> <CustLangPref>EN</CustLangPref>
              <ClientApp> <Org>IFBI</Org> <Name>OAM</Name> <Version>1.0</Version>
              </ClientApp> <ServerDt>2016-11-08T12:08:57.246-05:00</ServerDt> <SessKey>f99a5a5f267f496fb2a9fc6708069874</SessKey>
              <Language>EN</Language> </SignonRs> <InsuranceSvcRs> <RqUID>2b9e53f0-524c-4992-a56e-e0ce99be0eb7</RqUID>
              <PersAutoPolicyModRs> <RqUID>5098aaa9-5903-4f89-a4d2-57eb25c1cade</RqUID>
              <BusinessPurposeTypeCd>PCH</BusinessPurposeTypeCd> <TransactionResponseDt>2016-11-08T12:08:57.246-05:00</TransactionResponseDt>
              <TransactionEffectiveDt>2016-11-08T12:08:56.235-05:00</TransactionEffectiveDt>
              <CurCd>USD</CurCd> <MsgStatus> <MsgStatusCd>Success</MsgStatusCd> </MsgStatus>
              <ModInfo IdRef="Vehicle1"> <ActionCd>M</ActionCd> </ModInfo> <ModInfo
              IdRef="VehicleQuestion1"> <ActionCd>A</ActionCd> </ModInfo> <ModInfo
              IdRef="VehicleQuestion2"> <ActionCd>A</ActionCd> </ModInfo> <ModInfo
              IdRef="VehicleQuestion3"> <ActionCd>A</ActionCd> </ModInfo> <ModInfo
              IdRef="VehicleQuestion4"> <ActionCd>A</ActionCd> </ModInfo> <ModInfo
              IdRef="VehicleQuestion5"> <ActionCd>A</ActionCd> </ModInfo> <PersPolicy>
              <PolicyNumber>0008311523</PolicyNumber> <LOBCd>AUTOP</LOBCd> <ContractTerm>
              <EffectiveDt>2016-06-10</EffectiveDt> <ExpirationDt>2017-06-10</ExpirationDt>
              </ContractTerm> <QuoteInfo> <CompanysQuoteNumber>0008311523</CompanysQuoteNumber>
              <ItemIdInfo> <InsurerId>KVW1VZV7467SPREM</InsurerId> </ItemIdInfo> <IterationNumber>2</IterationNumber>
              <InsuredFullToBePaidAmt> <Amt>706.52</Amt> </InsuredFullToBePaidAmt>
              </QuoteInfo> </PersPolicy> <PersAutoLineBusiness> <LOBCd>AUTOP</LOBCd>
              <PersVeh id="Vehicle1"> <ManufacturerCd>CHEV</ManufacturerCd> <ModelCd>SILVSIL2KH</ModelCd>
              <ModelYear>2001</ModelYear> <VehBodyTypeCd>PU</VehBodyTypeCd> <InspectionInfo>
              <InspectionStatusCd>Completed</InspectionStatusCd> <VehInspectionInfo>
              <VehIdentificationNumber>1GCHK24191E314276</VehIdentificationNumber>
              </VehInspectionInfo> </InspectionInfo> <QuestionAnswer id="VehicleQuestion1">
              <QuestionCd>AUTOP01</QuestionCd> <YesNoCd>NO</YesNoCd> </QuestionAnswer>
              <QuestionAnswer id="VehicleQuestion2"> <QuestionCd>AUTOP11</QuestionCd>
              <YesNoCd>NO</YesNoCd> </QuestionAnswer> <QuestionAnswer id="VehicleQuestion3">
              <QuestionCd>AUPFL02</QuestionCd> <YesNoCd>NO</YesNoCd> </QuestionAnswer>
              <QuestionAnswer id="VehicleQuestion4"> <QuestionCd>AUTOB07</QuestionCd>
              <YesNoCd>NO</YesNoCd> </QuestionAnswer> <QuestionAnswer id="VehicleQuestion5">
              <QuestionCd>AUPMA14</QuestionCd> <YesNoCd>NO</YesNoCd> </QuestionAnswer>
              </PersVeh> </PersAutoLineBusiness> </PersAutoPolicyModRs> </InsuranceSvcRs>
              </ACORD>'}
  /PolicyChangeLimit:
    post:
      tags: [PolicyChangeLimit, Policy]
      summary: Changes one or more limits
      description: Based on some business logic, this changes limits when applicable
      operationId: JavaMethodName1
      consumes: [application/xml]
      produces: [applicaiton/xml]
      externalDocs: {description: 'Sample Request

          ', url: 'http://connections/issite/ews/SiteAssets/VehicleTransfer_And_VehicleQuestionsChange.xml'}
      responses:
        '200':
          description: coverage change response
          schema: {type: file}
